version: '2'
services:
  mailserver:
    image: hardware/mailserver
    container_name: mailserver
    domainname: nafia.ephec-ti.be
    hostname: mail
    ports:
      - "25:25"     # SMTP                - Required
      - "143:143"   # IMAP       STARTTLS - Optional - For webmails/desktop clients
      - "993:993"   # IMAPS      SSL/TLS  - Optional - For webmails/desktop clients
    environment:
      - DBPASS=myPassword
      - ENABLE_FETCHMAIL=true
    volumes:
      - /home/amine/docker/mail:/var/mail
      - /home/amine/docker/mail/opendkim:/etc/opendkim/keys
      - /home/amine/docker/nginx/certs/:/etc/letsencrypt
    depends_on:
      - mariadb

  # Administration interface
  postfixadmin:
    image: hardware/postfixadmin
    container_name: postfixadmin
    domainname: nafia.ephec-ti.be    
    hostname: mail
    environment:
      - DBPASS=password
    depends_on:
      - mailserver
      - mariadb

  # Web server
  nginx:
    image: wonderfall/boring-nginx
    container_name: nginx
    ports:
      - "80:8000"
      - "443:4430"
    volumes:
      - /home/amine/docker/nginx/sites-enabled:/sites-enabled
      - /home/amine/docker/nginx/conf:/conf.d
      - /home/amine/docker/nginx/log:/var/log/nginx
      - /home/amine/docker/nginx/certs:/certs
      - /home/amine/docker/nginx/www:/www
    depends_on:
      - postfixadmin

  # Database
  mariadb:
    image: mariadb:10.1
    container_name: mariadb
    # restart: always
    # Info : These variables are ignored when the volume already exists (databases created before).
    environment:
      - MYSQL_ROOT_PASSWORD=myPassword
      - MYSQL_DATABASE=postfix
      - MYSQL_USER=postfix
      - MYSQL_PASSWORD=myPassword
    volumes:
      - /home/amine/docker/mysql/db:/var/lib/mysql
